service:
  name: my-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "*"
  
functions:
  hello-world:
    handler: src/handlers/hello-world/hello-world.handler
    events:
      - http:
          method: get
          path: /hello-world
custom:
  jest:
    collectCoverage: true
